project:
  title: "Project One"
  type: website  # Change this from "book" to "website"
  output-dir: _output  # Keeps output organized

website:
  title: "Submission"  # Website title
  navbar:  # Defines the navigation menu
    left:
      - href: index.qmd
        text: Home
      - href: prac-day-1.qmd
        text: Practice Day 1
      - href: prac2.qmd
        text: Practice Day 2
      - href: prac-day-four.qmd
        text: Practice Day 4

format:
  html:
    theme: default
    toc: true  # Enables a Table of Contents on the side

editor: visual